### ISSUE TITLE
Server transits into readyness, even if socket not yet operational

### ISSUE THREAD

**Issue by blaggacao** [spiffe/spire-tutorials#35]
Consider the following script:
```shell
manifests=$(kustomize build 'github.com/spiffe/spire-tutorials/k8s/quickstart?ref=c6ab7c1058564b10cba75b182bcd2c436188df3b')
kubectl apply -f <(echo "$manifests")
sleep 25
kubectl wait --for=condition=Ready -n spire pod/spire-server-0 --timeout=120s
kubectl exec -n spire spire-server-0 -- \
	    /opt/spire/bin/spire-server entry create \
	    -spiffeID spiffe://example.or/ns/spire/sa/spire-agent \
	    -selector k8s_sat:cluster:demo-cluster \
	    -selector k8s_sat:agent_ns:spire \
	    -selector k8s_sat:agent_sa:spire-agent \
	    -node

```
On one occasion, it returned
```
FAILED to create the following entry:
Entry ID      :
SPIFFE ID     : spiffe://example.org/ns/spire/sa/spire-agent
Parent ID     : spiffe://example.org/spire/server
TTL           : 3600
Selector      : k8s_sat:cluster:demo-cluster
Selector      : k8s_sat:agent_ns:spire
Selector      : k8s_sat:agent_sa:spire-agent

rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial unix /tmp/spire-registration.sock: connect: no such file or directory"
command terminated with exit code 1
```
indicating that the container transitioned into Ready -- [see meaning](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-conditions) -- while the socket wasn't ready, yet.

Maybe this is a problem with the healthcheck command of the spire server itself, though? Or maybe an additional Readiness probe here could do the trick?

**Comment by lucianozablocki** [comment]
Hi @blaggacao and thanks for your feedback! We're currently working on this in #51. Check it out and let me know if it meet your needs.

Best regards,
Luciano

**Comment by blaggacao** [comment]
Hi @lucianozablocki Thank you for taking on this. It will be a while (2-3 months), before I can context switch back to where I was when reporting this issue. At any rate, thanks for pushing a potential solution.
