### ISSUE TITLE
k8s/envoy-x509/ frontend app is busted.  needs to use tether instead of poppler

### ISSUE THREAD

**Issue by devgig** [spiffe/spire-tutorials#36]
I was getting the following error.
bootstrap.min.js:7 Uncaught Error: Bootstrap tooltips require Tether (http://tether.io/)
I updated the container to include tether in the index.html and that fixed it, but I need the image updated because of security I need to turn off the hostPID = true.

**Comment by Andres-GC** [comment]
Hi devgig,
There is fix is already pushed for that. I'll update the tutorials with the new image shortly.

**Comment by Andres-GC** [comment]
devgig,

Images are updated now.

Regards.
