### ISSUE TITLE
CI/CD is not being run

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire-tutorials#73]
The org no longer uses Travis for CI/CD and this repository has not been updated to use github actions.

**Comment by sanderson042** [comment]
Hi @azdagron - I was wondering if this bug is fixed now due to PR #104 and other similar PRs? Though maybe PR #102 still needs to be modified and merged?

I hope things are going well for you. 😄

**Comment by azdagron** [comment]
Yep! This can be closed. Thanks for the ping, @sanderson042 !
