### ISSUE TITLE
Vault not validating JWT - /keys not being served

### ISSUE THREAD

**Issue by PhilCorney** [spiffe/spire-tutorials#86]
Hi,
I'm unable to get vault to integrate with SPIRE.
At the [Autenticate to Vault Server](https://github.com/spiffe/spire-tutorials/tree/main/k8s/oidc-vault#authenticate-to-vault-server) step. I can create a JWT token but vault cannot validate this.
```
curl --request POST --data @./payload.json http://localhost:8200/v1/auth/jwt/login
{"errors":["error validating token: error verifying token signature: fetching keys oidc: get keys failed: 500 Internal Server Error document not available\n"]}
```
I suspect this maybe connected to not being able to validate the signature:
```
curl https://oidc-discovery.mydomain./keys
document not available
```
The spire-oidc container has the following error

> level=warning msg="Failed to fetch bundle" error="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /tmp/spire-server/private/api.sock: connect: no such file or directory\""

I also tried this with with legacy configuration and I see the same error.
```
 registration_api {
        socket_path = "/run/spire/sockets/registration.sock"
    }
```
Many thanks
Phil

**Comment by azdagron** [comment]
That tutorial configuration seems broken at first glance but before I dig into specifics, what version of SPIRE and the oidc-discovery-provider are you using? The same as the tutorial (1.2.3 and 1.0.0, respectively)?

**Comment by PhilCorney** [comment]
Thanks Andrew
Yes - 
gcr.io/spiffe-io/spire-server:1.2.3
gcr.io/spiffe-io/oidc-discovery-provider:1.0.0

**Comment by PhilCorney** [comment]
Hi,
I resolved the issue upgrading to the server api and changing mount paths.
I'll create a pull request.

**Comment by PhilCorney** [comment]
This is now working thank you
