### ISSUE TITLE
K8S Quickstart - Deploy Spire Agent fails

### ISSUE THREAD

**Issue by bengrissinger** [spiffe/spire-tutorials#88]
Environment is Rancher Desktop 1.4.1 (latest).  MacOS Monterey 12.4

https://spiffe.io/docs/latest/try/getting-started-k8s/ 

Everything works as described until  Deploy Spire Agent steps

bengrissinger@Bens-MacBook-Pro quickstart % k get daemonset -n spire     
NAME          DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
spire-agent   1         1         0       1            0           <none>          23m

<img width="990" alt="image" src="https://user-images.githubusercontent.com/2236835/178780692-a8b07c2a-9c8d-4684-9848-e353a39a0d70.png">

a look at the daemonset deploy shows no logs for the spire-agent container, as its waiting for the wait-for-it container to check the spire-server is running, which it is and in the same spire namespace

bengrissinger@Bens-MacBook-Pro quickstart % k get svc -n spire 
NAME           TYPE       CLUSTER-IP    EXTERNAL-IP   PORT(S)          AGE
spire-server   NodePort   10.43.28.56   <none>        8081:31040/TCP   79m

I have tried to port forward the spire-server and tried setting env vars to help the agent find the spire-server but with no luck

Any help with this would be greatly appreciated

**Comment by bengrissinger** [comment]
wasnt able to reproduce, worked after resetting cluster

**Comment by mchurichi** [comment]
Hi Ben,

I just tried with exactly the same setup and it worked on the first run. Spire server service is reachable and agent is up. Reading your logs seems like the service was not even resolvable, which is weird since it was there (CNI plugin issue maybe?)

I'm closing this but please feel free to reopen it if it happens again or if you have more info.
